"""Retry pass for impossible-fragment SMILES in example_index.

Hypothesis (validated empirically): when v2's example_index has an entry
whose SMILES is empty / failed validation / has MW < 150, the IUPAC was
likely truncated, OCR-corrupted, or the LLM cut a name mid-word. A
targeted re-extraction with a wider chunk + reformulated prompt usually
recovers a valid IUPAC.

Two-attempt cascade per suspicious cid (user-approved):
    Attempt 1: focused single-cid prompt (~$0.003) on a 2k window
    Attempt 2: wider chunk (~$0.005) on a 6k window
Stops on first OPSIN-success with MW >= 150.

Idempotent — uses `iupac_burst_targeted` underneath, which caches by
chunk fingerprint. Re-runs are $0.

Patent-agnostic. No per-patent flags. Only fires on cids matching
`is_suspicious()`.
"""
from __future__ import annotations

import logging
import re
from pathlib import Path

from .iupac_to_smiles import _try_opsin
from .smiles_utils import get_inchikey, molecular_weight, validate_smiles
from .cost_tracker import cost_tracker
from .assay_fsm.harvest.iupac_orchestrator import (
    _chunk_fingerprint, _read_cache, _write_cache, _find_cid_context_windows,
)
from .assay_fsm.harvest.agent_iupac_extract import extract_iupac_pairs

logger = logging.getLogger(__name__)


# Floor for "this SMILES is too small to be a complete patented compound"
MIN_VALID_MW = 150.0

# Failure-reason prefixes that hint at recoverable extraction errors
_SUSPICIOUS_REASON_PREFIXES = (
    "smiles_too_short",            # truncated mid-name
    "mw_too_low",                  # likely fragment
    "rdkit_rejected_opsin_output", # OPSIN gave invalid SMILES
    "all_stages_failed",           # every cleanup stage failed
    "no_iupac_name",               # extraction itself missed
)

# OCR-error patterns in IUPAC text that signal "this name probably came
# from a noisy source; even if OPSIN accepted the cleaned variant,
# the resulting SMILES may correspond to the wrong molecule because
# the cleanup didn't catch every error."
_OCR_ARTIFACT_PATTERNS = re.compile(
    r"|".join([
        r"\bpyrolo\b",          # pyrolo → pyrrolo (missing 'r')
        r"\bpyrolol\b",         # pyrolol → pyrrolo (extra 'l')
        r"\bisoquinoin\b",      # isoquinoin → isoquinolin
        r"\bquinoxalin\b(?!e)", # quinoxalin (truncated; should be -ine)
        r"\bbenzimidazl\b",     # benzimidazl → benzimidazol
        r"\b1Hbenzimidazol\b",  # missing dash
        r"\\\*",                # markdown escape leftover
        r"!\[",                 # markdown image syntax
        r"--\s",                # double-dash
        r"\b\w+\s+\[\d+,\d+",   # space before bracket like "pyrolo [2,1"
    ]),
    re.IGNORECASE,
)


def is_suspicious(rec: dict) -> bool:
    """Decide whether an example_index entry warrants a retry.

    Verification BEFORE retry is intentional — we want to flag only
    entries whose SMILES is genuinely broken or missing. Entries with a
    valid, drug-MW SMILES are trusted even if the original IUPAC text
    had OCR markers; the retry would just re-extract the same compound
    via a slower path and burn LLM budget.

    A record is suspicious only if:
      - canonical_smiles is empty                       (must re-extract)
      - canonical_smiles fails RDKit validation         (corrupt)
      - SMILES MW < MIN_VALID_MW (150)                  (fragment, not drug)
      - iupac_name contains *severe* OCR markup tags
        (`<|ref|>`, `[[114,99,...]]`) AND the SMILES
        was generated by a stage downstream of OPSIN
        (rule_cleaned, llm_cleaned) — those are the
        only stages where the SMILES might be for a
        partial parse of a still-corrupted name
      - **MS m/z disagrees with stored SMILES MW** by more than ±5 Da
        — strong signal of cid-mapping drift (the IUPAC under this cid
        is for a different compound than HARVEST's assay row claims).
        This catches Strategy 4 TABLE-1 position-based cid drift and
        any other source where IUPAC and HARVEST'd cid disagree.

    Importantly, GP-embedded SMILES (extraction_method=`gp_embedded_meta`)
    and stages backed by canonical sources (`pubchem_direct`,
    `opsin_direct`) are NEVER suspicious as long as their SMILES is
    valid + drug-MW AND their MW agrees with MS — those came through
    a deterministic pipeline.
    """
    smi = (rec.get("canonical_smiles") or "").strip()
    method = (rec.get("extraction_method") or "").strip()

    # Empty / invalid / sub-drug SMILES → definitely retry
    if not smi:
        return True
    if not validate_smiles(smi):
        return True
    mw = molecular_weight(smi)
    if mw is None or mw < MIN_VALID_MW:
        return True

    # MS m/z cross-check (adaptive catch-all): if HARVEST extracted
    # an MS [M+H]+ value for this cid, the stored SMILES MW should
    # be within ±5 Da of (m/z − 1.008). If not, the cid-mapping is
    # almost certainly wrong — fire the LLM retry to recover the
    # correct (cid, IUPAC) pairing. Catches Strategy 4 position-based
    # drift, OCR-misread compound numbers, dual-stereo splits, etc.
    ms_mh = rec.get("ms_mh_plus_found") or rec.get("ms_mh_plus_calcd")
    try:
        ms_mh = float(ms_mh) if ms_mh is not None else None
    except (TypeError, ValueError):
        ms_mh = None
    if ms_mh is not None and ms_mh > 100:
        expected_mw = ms_mh - 1.008
        if abs(mw - expected_mw) > 5.0:
            return True

    # Trusted sources — never re-run regardless of IUPAC text (after
    # the MS check has already cleared them)
    if method in (
        "gp_embedded_meta", "pubchem_direct", "opsin_direct",
    ):
        return False

    # Untrusted stages: only flag if IUPAC text shows SEVERE OCR markup
    # (the residue characters that survive even after rule_clean stripped
    # the obvious tags). Anything else passes — minor pyrolo/typo cases
    # are recoverable inside the cascade and don't need a re-extraction.
    iupac = rec.get("iupac_name") or ""
    if re.search(r"<\|[a-z/_]+\|>|\[\[\s*\d+\s*,\s*\d+", iupac, re.IGNORECASE):
        return True

    # Recoverable failure reasons explicitly say "the extraction itself
    # didn't run" or "every stage failed without producing a SMILES".
    # If we got HERE, smi is non-empty, valid, and drug-MW, so those
    # prefixes shouldn't apply — sanity-check the reason anyway.
    fr = (rec.get("failure_reason") or "")
    if fr.startswith("no_iupac_name"):
        return True

    return False


def _build_retry_record(cid: str, iupac: str, smiles: str, attempt: int) -> dict:
    return {
        "compound_id": f"Cpd. No. {cid}",
        "iupac_name": iupac,
        "canonical_smiles": smiles,
        "inchikey": get_inchikey(smiles) or "",
        "source": f"retry_attempt_{attempt}",
        "extraction_method": f"impossible_fragment_retry_attempt_{attempt}",
    }


_FOCUSED_PROMPT = """\
You are reading a chemistry patent excerpt. The excerpt mentions
compound number {cid}. Extract the IUPAC chemical name for compound {cid}
from this text. Return ONLY the IUPAC name on a single line, no other
text. If the IUPAC isn't clearly present, return "UNKNOWN".

Excerpt:
---BEGIN---
{chunk}
---END---

The IUPAC for compound {cid}:"""


def _attempt1_focused(
    patent_id: str,
    text: str,
    cid: str,
    cache: dict,
) -> str:
    """Attempt 1: focused single-cid prompt, ~2k char window."""
    windows = _find_cid_context_windows(text, cid, window_chars=2000)
    if not windows:
        return ""
    offset, chunk = windows[0]
    fp = _chunk_fingerprint(chunk + f"|focused:{cid}")
    cache_key = f"retry_focused:{fp}"
    if cache_key in cache:
        cached = cache[cache_key]
        return cached.get("iupac", "")
    from .api_client import call_claude_text
    prompt = _FOCUSED_PROMPT.format(cid=cid, chunk=chunk)
    response = call_claude_text(
        prompt=prompt,
        patent_id=patent_id,
        max_tokens=300,
    )
    iupac = ""
    if response and "UNKNOWN" not in response.upper()[:30]:
        # Take first line; strip trailing punctuation
        iupac = response.strip().split("\n")[0].strip().rstrip(".")
    cache[cache_key] = {"iupac": iupac, "offset": offset}
    return iupac


def _attempt2_wide(
    patent_id: str,
    text: str,
    cid: str,
    cache: dict,
) -> str:
    """Attempt 2: wider chunk re-extract via the existing iupac_burst_targeted
    machinery. Returns the LLM-extracted IUPAC for `cid` or empty.
    """
    windows = _find_cid_context_windows(text, cid, window_chars=6000)
    if not windows:
        return ""
    offset, chunk = windows[0]
    fp = _chunk_fingerprint(chunk + f"|wide:{cid}")
    cache_key = f"retry_wide:{fp}"
    if cache_key in cache:
        cached = cache[cache_key]
        for p in cached.get("pairs", []):
            if p.get("compound_id") == cid:
                return p.get("iupac_name", "")
        return ""
    result = extract_iupac_pairs(chunk, patent_id=patent_id)
    cache[cache_key] = {
        "pairs": result.pairs,
        "_target_cid": cid,
        "_offset": offset,
    }
    for p in result.pairs:
        if p.get("compound_id") == cid:
            return p.get("iupac_name", "")
    return ""


def _opsin_with_validation(iupac: str) -> tuple[str, str]:
    """Run OPSIN + validate. Return (canonical_smiles, inchikey) or
    ('', '') if not a valid drug-like molecule (MW >= MIN_VALID_MW)."""
    if not iupac:
        return "", ""
    cleaned = re.sub(
        r"^(?:racemic|rac\.?|meso)\s+", "", iupac, flags=re.IGNORECASE,
    ).strip()
    smiles, _err = _try_opsin(cleaned)
    if not (smiles and validate_smiles(smiles)):
        return "", ""
    mw = molecular_weight(smiles)
    if mw is None or mw < MIN_VALID_MW:
        return "", ""
    return smiles, get_inchikey(smiles) or ""


def retry_impossible_fragments(
    patent_id: str,
    text: str,
    example_index: dict,
    *,
    budget_remaining_usd: float = 5.00,
    max_retries_per_cid: int = 2,  # kept for backwards-compat, unused
    max_runtime_s: float = 300.0,        # 5 min — enough for ~25-30 chunks
    max_suspicious_cids: int = 100,       # bumped from 50 — MS-MW gate
                                          # surfaces cid-drift cases too
) -> tuple[int, int, dict]:
    """Batched retry for suspicious example_index entries.

    Uses `iupac_burst_targeted` to fire ONE chunk-level LLM call per
    unique text window covering multiple cids — far faster than the
    per-cid focused+wide cascade we used previously.

    A cid is suspicious if `is_suspicious(rec)` returns True (empty
    SMILES, OPSIN-fail, sub-150 MW, severe OCR markup in IUPAC text).

    Args:
        patent_id: For cost attribution + cache scoping.
        text: Full patent text.
        example_index: cid → record dict. Mutated in place.
        budget_remaining_usd: Soft cap on LLM cost.
        max_runtime_s: Hard runtime cap. iupac_burst_targeted may run
            many chunks; we cap the wall-clock to keep the per-patent
            budget reasonable. Default 180s = 3 min.
        max_suspicious_cids: If `is_suspicious` flags more than this many
            cids, only retry the first N (sorted by cid length then
            string). Prevents runaway retries on malformed patents
            where verification flagged hundreds of false positives.

    Returns:
        (n_attempted, n_recovered, updated_example_index).
        n_attempted = number of chunk-level LLM calls (or pairs returned).
        n_recovered = cids whose SMILES improved this round.
    """
    import time

    suspicious_cids = sorted(
        [cid for cid, rec in example_index.items() if is_suspicious(rec)],
        key=lambda s: (len(s), s),
    )
    if not suspicious_cids:
        logger.info("%s: no suspicious cids — retry pass not needed", patent_id)
        return 0, 0, example_index

    if len(suspicious_cids) > max_suspicious_cids:
        logger.warning(
            "%s: %d suspicious cids exceeds cap %d — capping to first %d",
            patent_id, len(suspicious_cids), max_suspicious_cids,
            max_suspicious_cids,
        )
        suspicious_cids = suspicious_cids[:max_suspicious_cids]

    logger.info(
        "%s: %d suspicious cids — batched retry (budget $%.2f, runtime cap %.0fs)",
        patent_id, len(suspicious_cids), budget_remaining_usd, max_runtime_s,
    )
    t_start = time.time()

    initial_spend = cost_tracker.patent_spend(patent_id)
    n_recovered = 0

    # Single batched call: iupac_burst_targeted groups overlapping cid
    # windows so multiple cids share one LLM chunk. Far faster than
    # per-cid serial firing (60+ chunks vs 600+).
    from .assay_fsm.harvest.iupac_orchestrator import iupac_burst_targeted
    new_pairs = iupac_burst_targeted(
        patent_id=patent_id,
        text=text,
        missing_cids=suspicious_cids,
        cost_tracker=cost_tracker,
        window_chars=8000,
    )

    # Merge: only overwrite if the new IUPAC OPSIN-resolves to a valid
    # SMILES with MW >= 150 — same gate as is_suspicious's MW floor.
    for cid, iupac in new_pairs.items():
        if cost_tracker.patent_spend(patent_id) - initial_spend > budget_remaining_usd:
            logger.info(
                "%s: retry budget hit ($%.4f) — skipping further merges",
                patent_id,
                cost_tracker.patent_spend(patent_id) - initial_spend,
            )
            break
        if time.time() - t_start > max_runtime_s:
            logger.info(
                "%s: retry runtime cap hit (%.0fs) — skipping further merges",
                patent_id, max_runtime_s,
            )
            break
        smiles, ik = _opsin_with_validation(iupac)
        if not smiles:
            continue
        example_index[cid] = _build_retry_record(cid, iupac, smiles, attempt=1)
        n_recovered += 1

    n_attempted = len(new_pairs)
    final_spend = cost_tracker.patent_spend(patent_id) - initial_spend
    logger.info(
        "%s: retry pass complete — %d pairs returned, %d recovered, $%.4f spent",
        patent_id, n_attempted, n_recovered, final_spend,
    )
    return n_attempted, n_recovered, example_index
